### ISSUE TITLE
'StyledCodeMirrorEditor' is not defined

### ISSUE THREAD

**Issue by ghost** [jamesknelson/use-codemirror#2]
I don't understand the front page example which returns a StyledCodeMirrorEditor which does not seem to be defined anywhere.

**Comment by jamesknelson** [comment]
StyledCodeMirrorEditor is meant to be a placeholder for your own component that sets up the styles for the editor component. For an example, see the example directory.

**Comment by ghost** [comment]
Presence of example code explains this.
